import os
import json

def load_art_database():
    """예술 DB를 불러오는 함수"""
    current_dir = os.path.dirname(os.path.abspath(__file__))  
    file_path = os.path.join(current_dir, "data", "labels_with_image_paths.json")
    
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"❌ 예술 DB를 찾을 수 없습니다: {file_path}")

    with open(file_path, "r", encoding="utf-8") as f:
        return json.load(f)
    
# 작품 정보 검색 함수
def search_artwork_by_title(title):
    """
    작품 제목을 기반으로 RAG 문서에서 artist, period, webpage 정보를 검색하는 함수.
    """
    art_database = load_art_database()
    
    for entry in art_database:
        if entry["title"].lower() == title.lower():  # 대소문자 구분 없이 비교
            artist = entry["artist_display_name"]
            title_translations, artist_translations = create_translation_mappings(title, artist)
            
            return {
                "title": title_translations if title_translations else title,
                "artist": artist_translations if artist_translations else artist,
                "period": entry["period"],
                "webpage": entry["webpage"]
            }
    
    # 해당 작품이 없을 경우 Untitled로 처리
    return None

def create_translation_mappings(title, artist):
    """
    영문 작가명과 작품명을 한국어로 변환하기 위한 매핑 사전을 생성합니다.
    """
    # 작가명 매핑 (영문 -> 한국어)
    ARTIST_TRANSLATIONS = {
        # 서양 작가
        "Vincent van Gogh": "빈센트 반 고흐",
        "Leonardo da Vinci": "레오나르도 다 빈치",
        "Claude Monet": "클로드 모네",
        "Rembrandt (Rembrandt van Rijn)": "렘브란트",
        "Rembrandt van Rijn": "렘브란트",
        "Pablo Picasso": "파블로 피카소",
        "Michelangelo Buonarroti": "미켈란젤로",
        "Raphael (Raffaello Sanzio or Santi)": "라파엘로",
        "Raphael": "라파엘로",
        "Johannes Vermeer": "요하네스 베르메르",
        "Paul Cézanne": "폴 세잔",
        "Paul Gauguin": "폴 고갱",
        "Albrecht Dürer": "알브레히트 뒤러",
        "Caravaggio (Michelangelo Merisi)": "카라바조",
        "Caravaggio": "카라바조",
        "El Greco (Domenikos Theotokopoulos)": "엘 그레코",
        "El Greco": "엘 그레코",
        "Édouard Manet": "에두아르 마네",
        "Peter Paul Rubens": "페테르 파울 루벤스",
        "Edgar Degas": "에드가 드가",
        "Giotto di Bondone": "조토",
        "Gustav Klimt": "구스타프 클림트",
        "Titian (Tiziano Vecellio)": "티치아노",
        "Titian": "티치아노",
        "Henri de Toulouse-Lautrec": "앙리 드 툴루즈 로트렉",
        "Henri Rousseau (le Douanier)": "앙리 루소",
        "Goya (Francisco de Goya y Lucientes)": "프란시스코 고야",
        "Francisco de Goya": "프란시스코 고야",
        "Auguste Renoir": "오귀스트 르누아르",
        "Georges Seurat": "조르주 쇠라",
        "Joseph Mallord William Turner": "윌리엄 터너",
        "Caspar David Friedrich": "카스파어 다비드 프리드리히",
        "John Constable": "존 컨스터블",
        "Jacques Louis David": "자크 루이 다비드",
        "Jean Auguste Dominique Ingres": "장 오귀스트 도미니크 앵그르",
        "Nicolas Poussin": "니콜라 푸생",
        "Claude Lorrain (Claude Gellée)": "클로드 로랭",
        "Eugène Delacroix": "외젠 들라크루아",
        "Francisco de Zurbarán": "프란시스코 데 수르바란",
        "Hans Memling": "한스 멤링",
        "Petrus Christus": "페트루스 크리스투스",
        "Botticelli (Alessandro di Mariano Filipepi)": "산드로 보티첼리",
        "Botticelli": "산드로 보티첼리",
        "Egon Schiele": "에곤 실레",
        "Hans Holbein the Younger": "한스 홀바인",
        "Amedeo Modigliani": "아메데오 모딜리아니",
        "Paul Klee": "파울 클레이",
        "Camille Corot": "카미유 코로",
        "Gustave Courbet": "귀스타브 쿠르베",
        "Honoré Daumier": "오노레 도미에",
        "Pieter Bruegel the Elder": "피터 브뤼겔",
        "Michel Henry": "미셸 앙리",
        "James McNeill Whistler": "제임스 맥닐 휘슬러",
        "Mary Cassatt": "메리 카사트",
        "John Singer Sargent": "존 싱어 사전트",
        "Frederic Edwin Church": "프레데릭 에드윈 처치",
        "Winslow Homer": "윈슬로 호머",
        "Thomas Cole": "토마스 콜",
        
        # 추가 작가
        "Han Gan": "한간",
        "Wu Bin": "오빈",
        "Gong Xian": "공현",
        "Wang Hui": "왕휘",
        "Qian Xuan": "전선",
        "Guo Xi": "곽희",
        "Emperor Huizong": "송 휘종",
        "Qu Ding": "곽정",
        "Kano Sansetsu": "가노 산세츠",
        "Canaletto (Giovanni Antonio Canal)": "카날레토",
        "Fra Filippo Lippi": "프라 필리포 리피",
        "Duccio di Buoninsegna": "두초",
        "Andrea Mantegna": "안드레아 만테냐",
        "Simone Martini": "시모네 마르티니",
        "Giovanni Bellini": "조반니 벨리니",
        "Rogier van der Weyden": "로히어 판 데르 바이덴",
        "Gerard David": "헤라르트 다비드",
        "Jan van Eyck": "얀 판 에이크",
        "Hans Baldung (called Hans Baldung Grien)": "한스 발둥",
        "Anthony van Dyck": "안토니 반 다이크",
        "Vasily Kandinsky": "바실리 칸딘스키",
        "Francis William Edmond" : "프란시스 윌리엄 에드먼즈",
        "John Vanderlyn" : "존 반더린",
        "William Sidney Mount" : "윌리엄 시드니 마운트",
        "Asher Brown Durand" : "애셔 브라운 듀랜드",
        "Charles Willson Peale" : "찰스 윌슨 필",
        "George Inness" : "조지 이네스",
        "George Caleb Bingham" : "조지 캘럽 빙엄",
        "Thomas Anshutz" : "토마스 앤슈츠",
        "James Peale" : "제임스 필",
        "Childe Hassam" : "차일드 해섬",
        "William James Glackens" : "윌리엄 제임스 글래킨스",
        "Gilbert Stuart" : "길버트 스튜어트",
        "Ralph Earl" : "랄프 얼",
        "Cecilia Beaux" : "세실리아 보",
        "Rembrandt Peale" : "렘브란트 필",
        "Thomas Eakins" : "토마스 에이킨스",
        "Lawrence Kilburn (or Kilbrunn)" : "로렌스 킬번(또는 킬브룬)",
        "Unidentified Artist" : "작가 미상",
        "Bhawani Das" : "바와니 다스",
        "Jasper Francis Cropsey" : "재스퍼 프란시스 크롭시",
        "Félix Vallotton" : "펠릭스 발로통",
        "George Bellows" : "조지 벨로우스"
    }
    
    # 작품명 매핑 (영문 -> 한국어)
    TITLE_TRANSLATIONS = {
        # 유명 작품
        "Mona Lisa": "모나리자",
        "The Last Supper": "최후의 만찬",
        "The Starry Night": "별이 빛나는 밤",
        "Night-Shining White": "조백마도",
        "The Sixteen Luohans": "십육나한도",
        "Ink Landscapes with Poems": "시가 있는 수묵 풍경화",
        "The Kangxi Emperor's Southern Inspection Tour, Scroll Three": "강희제 남순행도 3권",
        "Wang Xizhi watching geese": "왕희지 관아도",
        "Old Trees, Level Distance": "고목평원도",
        "Finches and bamboo": "문조죽도",
        "Summer Mountains": "하산도",
        "Old Plum": "고매도",
        "Clothing the Naked": "벌거벗은 이들에게 옷을 입히다",
        "Lucas van Uffel (died 1637)": "루카스 판 우펠 (1637년 사망)",
        "Rubens, His Wife Helena Fourment (1614–1673), and Their Son Frans (1633–1678)": "루벤스, 그의 아내 헬레나 푸르멘트(1614-1673), 그리고 그들의 아들 프란스(1633-1678)",
        "The Holy Family with Saints Anne and Catherine of Alexandria": "성녀 안나와 알렉산드리아의 성녀 카타리나와 함께 있는 성가족",
        "Juan de Pareja (1606–1670)": "후안 데 파레하 (1606-1670)",
        "Virgin and Child": "성모자상",
        "Mäda Primavesi (1903–2000)": "메다 프리마베지 (1903-2000)",
        "Manuel Osorio Manrique de Zuñiga (1784–1792)": "마누엘 오소리오 만리케 데 수니가 (1784-1792)",
        "The Young Virgin": "젊은 성모",
        "Island of the Dead": "죽음의 섬",
        "Cardinal Fernando Niño de Guevara (1541–1609)": "추기경 페르난도 니뇨 데 게바라 (1541-1609)",
        "View of Toledo": "톨레도 풍경",
        "Young Woman with a Water Pitcher": "물주전자를 든 젊은 여인",
        "Study of a Young Woman": "젊은 여인의 연구",
        "Merry Company on a Terrace": "테라스의 유쾌한 일행",
        "Aristotle with a Bust of Homer": "호메로스의 흉상과 함께 있는 아리스토텔레스",
        "Self-Portrait": "자화상",
        "Young Man and Woman in an Inn (Yonker Ramp and His Sweetheart)": "여관에서의 젊은 남녀 (용커 램프와 그의 연인)",
        "Merrymakers at Shrovetide": "사육제의 유쾌한 사람들",
        "The Crucifixion with the Virgin and Saint John": "성모와 성 요한이 있는 십자가 처형",
        "Wheat Fields": "밀밭",
        "Cypresses": "사이프러스",
        "Wheat Field with Cypresses": "사이프러스가 있는 밀밭",
        "The Repast of the Lion": "사자의 식사",
        "Soap Bubbles": "비누 거품",
        "The Toilette of Venus": "비너스의 화장",
        "Sibylle": "시빌",
        "Mademoiselle V. . . in the Costume of an Espada": "투우사 복장을 한 마드무아젤 V...",
        "Boating": "보트 타기",
        "The Dance Class": "무용 수업",
        "Circus Sideshow (Parade de cirque)": "서커스 부속 행사",
        "Evening Landscape with an Aqueduct": "수로가 있는 저녁 풍경",
        "The Love Letter": "연애 편지",
        "Bashi-Bazouk": "바시바주크",
        "Garden at Sainte-Adresse": "생타드레스의 정원",
        "Broken Eggs": "깨진 계란",
        "The Death of Socrates": "소크라테스의 죽음",
        "Antoine-Laurent Lavoisier (1743–1794) and His Wife": "앙투안 로랑 라부아지에(1743-1794)와 그의 아내",
        "Madame Jacques-Louis Leblanc (Françoise Poncelle, 1788–1839)": "자크 루이 르블랑 부인 (프랑수아즈 퐁셀, 1788-1839)",
        "Joseph-Antoine Moltedo (born 1775)": "조제프 앙투안 몰테도 (1775년생)",
        "The Horse Fair": "말 시장",
        "The Trojan Women Setting Fire to Their Fleet": "함대에 불을 지르는 트로이 여인들",
        "Joan of Arc": "잔 다르크",
        "The Abduction of the Sabine Women": "사비니 여인들의 약탈",
        "Blind Orion Searching for the Rising Sun": "떠오르는 태양을 찾는 장님 오리온",
        "The Third-Class Carriage": "3등석 객차",
        "Madame Georges Charpentier and Her Children": "조르주 샤르팡티에 부인과 그녀의 아이들",
        "Woman with a Parrot": "앵무새가 있는 여인",
        "Lute Player": "류트 연주자",
        "The Sofa": "소파",
        "The Fortune-Teller": "점쟁이",
        "The Abduction of Rebecca": "레베카의 납치",
        "Mezzetin": "메제탱",
        "Still Life with Apples and a Pot of Primroses": "사과와 앵초 냄비가 있는 정물",
        "The Card Players": "카드 놀이하는 사람들",
        "Still Life with Jar, Cup, and Apples": "항아리, 컵, 사과가 있는 정물",
        "Ia Orana Maria (Hail Mary)": "이아 오라나 마리아 (성모 찬송)",
        "The Judgment of Paris": "파리스의 심판",
        "Hermann von Wedigh III (died 1560)": "헤르만 폰 베디히 3세 (1560년 사망)",
        "Two Men Contemplating the Moon": "달을 바라보는 두 남자",
        "Virgin and Child with Saint Anne": "성 안나와 함께 있는 성모자",
        "Saint John on Patmos": "파트모스의 성 요한",
        "Whalers": "포경선",
        "Venice, from the Porch of Madonna della Salute": "마돈나 델라 살루테의 현관에서 본 베니스",
        "Elizabeth Farren": "엘리자베스 패런",
        "Mrs. Grace Dalrymple Elliott (1754–1823)": "그레이스 달림플 엘리엇 부인 (1754-1823)",
        "Captain George K. H. Coussmaker (1759–1801)": "조지 K. H. 코스메이커 대위 (1759-1801)",
        "The Love Song": "사랑의 노래",
        "Salisbury Cathedral from the Bishop's Grounds": "주교의 뜰에서 본 솔즈베리 대성당",
        "The Crucifixion": "십자가형",
        "Madonna and Child Enthroned with Saints": "성인들과 함께 있는, 왕좌에 앉은 성모자",
        "The Coronation of the Virgin": "성모 대관식",
        "Samson Captured by the Philistines": "블레셋인들에게 잡힌 삼손",
        "Allegory of the Planets and Continents": "행성과 대륙의 알레고리",
        "Piazza San Marco": "산 마르코 광장",
        "Mars and Venus United by Love": "사랑으로 하나 된 마르스와 비너스",
        "The Adoration of the Magi": "동방박사의 경배",
        "A Hunting Scene": "사냥 장면",
        "Portrait of a Young Man": "젊은 남자의 초상",
        "The Last Communion of Saint Jerome": "성 제롬의 마지막 성찬",
        "Portrait of a Woman with a Man at a Casement": "창가의 남자와 함께 있는 여인의 초상",
        "The Meditation on the Passion": "수난에 관한 명상",
        "The Adoration of the Shepherds": "목자들의 경배",
        "Saint Andrew": "성 안드레아",
        "The Musicians": "음악가들",
        "The Denial of Saint Peter": "성 베드로의 부인",
        "The Holy Family with the Young Saint John the Baptist": "어린 세례자 요한과 함께 있는 성가족",
        "Venus and Cupid": "비너스와 큐피드",
        "Venus and Adonis": "비너스와 아도니스",
        "The Crucifixion- The Last Judgment": "십자가형과 최후의 심판",
        "The Rest on the Flight into Egypt": "이집트로 피신 중 쉬는 성가족",
        "Francesco d'Este (born about 1430, died after 1475)": "프란체스코 데스테 (약 1430년생, 1475년 이후 사망)",
        "The Harvesters": "수확하는 사람들",
        "Tommaso di Folco Portinari-Maria Portinari": "토마소 디 폴코 포르티나리-마리아 포르티나리",
        "The Penitence of Saint Jerome": "성 제롬의 참회",
        "Portrait of a Carthusian": "카르투시오회 수도사의 초상",
        "The Genius of Castiglione": "카스틸리오네의 천재성",
        "The Kaunitz Sisters (Leopoldine, Caroline, and Ferdinandine)": "카우니츠 자매들 (레오폴딘, 캐롤라인, 페르디난딘)",
        "Self-Portrait, from The Iconography": "도상학에서의 자화상",
        "A Giant Seated in a Landscape": "풍경 속에 앉아 있는 거인",
        "Portrait of Nicolas Trigault in Chinese Costume": "중국 복장을 한 니콜라스 트리고의 초상",
        "Summer Morning": "여름 아침",
        "Lady Lilith": "릴리스 부인",
        "Christ Crucified between the Two Thieves": "두 도둑 사이에서 십자가에 못 박힌 그리스도",
        "Reclining Female Nude": "누워 있는 여인의 누드",
        "Reading the News at the Weavers' Cottage": "직공의 오두막에서 뉴스를 읽는 모습",
        "Cottage among Trees": "나무들 사이의 오두막",
        "Dune Landscape with Oak Tree": "참나무가 있는 모래 언덕 풍경",
        "Corridor in the Asylum": "정신병원의 복도",
        "Aman-Jean (Portrait of Edmond François Aman-Jean)": "아망 장 (에드몬드 프랑수아 아망 장의 초상)",
        "Leonidas at Thermopylae": "테르모필레의 레오니다스",
        "Queen Esther Approaching the Palace of Ahasuerus": "아하수에로 왕궁에 접근하는 에스더 여왕",
        "Bacchanal": "바카날",
        "Portrait of an Ecclesiastic": "성직자의 초상",
        "The Connoisseur": "감정가",
        "Saada, the Wife of Abraham Ben-Chimol, and Préciada, One of Their Daughters": "사다, 아브라함 벤 키몰의 아내, 그리고 그들의 딸 중 하나인 프레시아다",
        "Head of a Man": "남자의 머리",
        "Tahitian Faces (Frontal View and Profiles)": "타히티인의 얼굴들 (정면과 측면)",
        "Adam and Eve": "아담과 이브",
        "Melencolia I": "멜랑콜리아 I",
        "Christ Carrying the Cross": "십자가를 지고 가는 그리스도",
        "The Entrance Hall of the Regensburg Synagogue": "레겐스부르크 회당의 입구 홀",
        "Landscape with a Double Spruce in the Foreground": "전경에 이중 가문비나무가 있는 풍경",
        "Samson and Delilah": "삼손과 들릴라",
        "The Lake of Zug": "추크 호수",
        "Imaginary View of Venice (undivided plate)": "베니스의 상상도 (미분할 플레이트)",
        "Bacchanal with a Wine Vat": "포도주 통과 함께 있는 바카날",
        "Lucretia": "루크레티아",
        "Studies for the Libyan Sibyl (recto)": "리비아의 시빌을 위한 연구 (앞면)",
        "Youth Playing a Pipe for a Satyr": "사티로스를 위해 파이프 연주하는 젊은이",
        "Jupiter and Juno": "주피터와 주노",
        "Scalinata della Trinità dei Monti": "트리니타 데이 몬티의 계단",
        "The Head of the Virgin in Three-Quarter View Facing Right": "오른쪽을 향한 3/4 측면의 성모 머리",
        "Compositional Sketches for the Virgin Adoring the Christ Child": "아기 예수를 경배하는 성모를 위한 구성 스케치",
        "Three Standing Figures (recto)": "서 있는 세 인물 (앞면)",
        "The Doorway": "문간",
        "Nocturne-The Thames at Battersea": "녹턴-배터시의 템스 강",
        "Woman Bathing (La Toilette)": "목욕하는 여인 (화장실)",
        "Édouard Manet, Seated, Holding His Hat": "앉아서 모자를 든 에두아르 마네",
        "Diana and Actaeon": "디아나와 악테온",
        "View of Heidelberg": "하이델베르크 풍경",
        "Otto, Count of Nassau and his Wife Adelheid van Vianen": "나사우의 백작 오토와 그의 아내 아델하이드 판 비아넨",
        "Hercules chasing Avarice from the Temple of the Muses": "뮤즈의 신전에서 탐욕을 쫓아내는 헤라클레스",
        "The Judgment of Paris": "파리스의 심판",
        "The Round Tower, from 'Carceri d'invenzione'": "'상상의 감옥'에서의 원형 탑",
        "Portrait of Monsieur Aublet": "오블레 씨의 초상",
        "Bust of Pseudo-Seneca": "가짜 세네카의 흉상",
        "Condesa de Altamira and Her Daughter, María Agustina": "알타미라 백작 부인과 그녀의 딸, 마리아 아구스티나",
        "Christ Carrying the Cross": "십자가를 지고 가는 그리스도",
        "Saint Jerome as Scholar": "학자로서의 성 제롬",
        "The Feast of Herod and the Beheading of the Baptist": "헤롯의 잔치와 세례자 요한의 참수",
        "Portrait of a Man, possibly Matteo di Sebastiano di Bernardino Gozzadini": "남자의 초상, 아마도 마테오 디 세바스티아노 디 베르나르디노 고차디니",
        "Portrait of a Woman, possibly Ginevra d'Antonio Lupari Gozzadini": "여인의 초상, 아마도 지네브라 단토니오 루파리 고차디니",
        "Cottage near the Entrance to a Wood": "숲 입구 근처의 오두막",
        "The Last Supper, after Leonardo da Vinci": "레오나르도 다 빈치의 최후의 만찬을 따라",
        "Satire on Art Criticism": "미술 비평에 대한 풍자",
        "Road in Etten": "에텐의 길",
        "Burgomaster Jan van Duren (1613–1687)": "얀 판 듀렌 시장 (1613-1687)",
        "Margaretha van Haexbergen (1614–1676)": "마르가레타 판 핵스베르겐 (1614-1676)",
        "Portrait of Gerard de Lairesse": "헤라르트 데 레레스의 초상",
        "Leisure Time in an Elegant Setting": "우아한 환경에서의 여가 시간",
        "Madame Roulin and Her Baby": "루랭 부인과 그녀의 아기",
        "Study for 'Poseuses'": "'자세를 취하는 사람들'을 위한 연구",
        "The Dining Room": "식당",
        "Madame Félix Gallois": "펠릭스 갈루아 부인",
        "Perseus and the Origin of Coral": "페르세우스와 산호의 기원",
        "Landscape with Stars": "별이 있는 풍경",
        "At the Circus- The Spanish Walk": "서커스에서-스페인식 워킹",
        "Seated Woman": "앉아 있는 여인",
        "Diana and Actaeon (Diana Surprised in Her Bath)": "디아나와 악테온 (목욕 중 놀란 디아나)",
        "Evening Calm, Concarneau, Opus 220 (Allegro Maestoso)": "저녁의 고요, 콩카르노, 작품 220 (알레그로 마에스토소)",
        "Houses on the Achterzaan": "아흐터잔의 집들",
        "Princesse de Broglie": "브로글리 공주",
        "Mme Vuillard Sewing by the Window, rue Truffaut": "트뤼포 거리, 창가에서 바느질하는 뷔야르 부인",
        "Young Girl Bathing": "목욕하는 소녀",
        "Two Young Girls at the Piano": "피아노 앞의 두 소녀",
        "Trees and Houses Near the Jas de Bouffan": "자스 드 부팡 근처의 나무들과 집들",
        "Head of a Young Woman": "젊은 여인의 머리",
        "Bust of a Man in a Hat Gazing Upward": "모자를 쓰고 위를 바라보는 남자의 흉상",
        "Ecstatic Christ": "황홀경의 그리스도",
        "Erasmus of Rotterdam": "로테르담의 에라스무스",
        "Three Virtues and Studies of a Seated Man": "세 가지 미덕과 앉아 있는 남자의 연구",
        "Saints Bartholomew and Simon": "성 바르톨로메오와 성 시몬",
        "Design for a Wall Monument": "벽 기념비를 위한 디자인",
        "Bacchus and Ariadne": "바쿠스와 아리아드네",
        "Warwick Castle- The East Front": "워릭 성-동쪽 전면",
        "Panaromic View of the Bacino di San Marco, Looking up the Giudecca Canal": "산 마르코 분지의 파노라마 전망, 주데카 운하를 바라보며",
        "The Burial of Punchinello": "펀치넬로의 장례",
        "The Betrothal of the Virgin": "성모의 약혼",
        "A Bear Walking": "걷는 곰",
        "Approach to a Mountain Village with Horsemen on the Road": "길에 기마병이 있는 산악 마을로의 접근",
        "Study for the Equestrian Monument to Francesco Sforza": "프란체스코 스포르차를 위한 기마상 연구",
        "The Martyrdom of Saint Paul": "성 바울의 순교",
        "The Creation of the World and the Expulsion from Paradise": "세계의 창조와 낙원에서의 추방",
        "The Annunciation to Zacharias- (verso) The Angel of the Annunciation": "자카리아스에게의 수태고지-(뒷면) 수태고지의 천사",
        "Coronation of the Virgin": "성모 대관식",
        "Madonna and Child": "성모자상",
        "The Annunciation": "수태고지",
        "The Adoration of the Magi": "동방박사의 경배",
        "The Assumption of the Virgin": "성모 승천",
        "The Last Supper": "최후의 만찬",
        "The Coronation of the Virgin": "성모 대관식",
        "The Nativity": "성탄",
        "Saint Anthony the Abbot in the Wilderness": "광야의 성 안토니 수도원장",
        "Portrait of a Woman, Possibly a Nun of San Secondo- (verso) Scene in Grisaille": "여인의 초상, 아마도 산 세콘도의 수녀-(뒷면) 그리자이유의 장면",
        "Portrait of Alvise Contarini- (verso) A Tethered Roebuck": "알비세 콘타리니의 초상-(뒷면) 줄에 매인 수사슴",
        "Large Boston Public Garden Sketchbook": "대형 보스턴 공공 정원 스케치북",
        "Men Shoveling Chairs (Scupstoel)": "의자를 삽질하는 남자들 (스쿠프스툴)",
        "Christ Carrying the Cross, with the Crucifixion": "십자가를 지고 가는 그리스도, 십자가형과 함께",
        "Archangel Gabriel- The Virgin Annunciate": "대천사 가브리엘-수태고지를 받는 성모",
        "Margaret of Austria": "오스트리아의 마가렛",
        "The Annunciation": "수태고지",
        "A Goldsmith in his Shop": "작업실의 금세공인",
        "Seated Woman, Back View": "뒷모습의 앉아 있는 여인",
        "Temple Gardens": "사원 정원",
        "Improvisation 27 (Garden of Love II)": "즉흥곡 27 (사랑의 정원 II)",
        "May Picture": "5월의 그림",
        "Portrait of a German Officer": "독일 장교의 초상",
        "Mt. Katahdin (Maine), Autumn #2": "카타딘 산 (메인), 가을 #2",
        "Wisconsin Landscape": "위스콘신 풍경",
        "I Saw the Figure 5 in Gold": "금색으로 5라는 숫자를 보았다",
        "Lady of the Lake": "호수의 숙녀",
        "The Entombment of Christ": "그리스도의 매장",
        "The Virgin of Guadalupe with the Four Apparitions": "네 가지 발현과 함께 있는 과달루페의 성모",
        "The Flower Girl": "꽃 파는 소녀",
        "Washington Crossing the Delaware": "델라웨어 강을 건너는 워싱턴",
        "Francis Brinley": "프랜시스 브린리",
        "Mrs. Francis Brinley and Her Son Francis": "프랜시스 브린리 부인과 그녀의 아들 프랜시스",
        "Mr. and Mrs. Daniel Otis and Child": "다니엘 오티스 부부와 자녀",
        "Lady with Her Pets (Molly Wales Fobes)": "애완동물과 함께 있는 숙녀 (몰리 웨일스 포브스)",
        "Still Life with Cake": "케이크가 있는 정물",
        "Euphemia White Van Rensselaer": "유피미아 화이트 밴 렌셀러",
        "The Trout Pool": "송어 웅덩이",
        "The Contest for the Bouquet": "꽃다발을 위한 경쟁",
        "Mary Sylvester": "메리 실베스터",
        "Woman in a Blue Dress": "파란 드레스를 입은 여인",
        "Allan Melville": "앨런 멜빌",
        "Winter Scene in Moonlight": "달빛 아래의 겨울 풍경",
        "Hugh Hall": "휴 홀",
        "Note in Pink and Brown": "분홍색과 갈색의 노트",
        "Variations in Violet and Grey—Market Place, Dieppe": "바이올렛과 회색의 변주곡-디에프의 시장",
        "Maternity": "모성",
        "The Great Statue of Amida Buddha at Kamakura": "가마쿠라의 아미타 대불",
        "Fishing Boats, Key West": "키 웨스트의 어선들",
        "A Basket of Clams": "조개 바구니",
        "Boys in a Dory": "도리에 있는 소년들",
        "Moonlight on Mount Lafayette, New Hampshire": "뉴햄프셔, 마운트 라파예트의 달빛",
        "Portrait of the Artist": "화가의 자화상",
        "The American School": "미국 학교",
        "The Falls of Niagara": "나이아가라 폭포",
        "Stage Fort across Gloucester Harbor": "글로스터 항구를 가로지르는 스테이지 포트",
        "Approaching Thunder Storm": "다가오는 뇌우",
        "A Gorge in the Mountains (Kauterskill Clove)": "산속 협곡 (카우터스킬 클로브)",
        "The Rocky Mountains, Lander's Peak": "록키 산맥, 랜더스 피크",
        "The Hatch Family": "해치 가족",
        "Portrait of a Gentleman": "신사의 초상",
        "Daniel Crommelin Verplanck": "다니엘 크로멜린 버플랭크",
        "Mrs. John Winthrop": "존 윈스럽 부인",
        "Midshipman Augustus Brine": "견습 해군 장교 오거스투스 브라인",
        "Arrangement in Flesh Colour and Black": "살색과 검정색의 배열",
        "View from Mount Holyoke, Northampton, Massachusetts, after a Thunderstorm": "뇌우 후, 매사추세츠 노스햄프턴, 마운트 홀리오크에서의 전망",
        "The Titan's Goblet": "타이탄의 술잔",
        "The Sortie Made by the Garrison of Gibraltar": "지브롤터 수비대의 출격",
        "Apple Blossoms": "사과 꽃",
        "Twilight on the Sound, Darien, Connecticut": "코네티컷 대리언, 사운드의 황혼",
        "Lake George": "조지 호수",
        "Flight Into Egypt": "이집트로의 피신",
        "At the Seaside": "해변에서",
        "Portrait of the Painter": "화가의 초상",
        "Susan Walker Morse (The Muse)": "수잔 워커 모스 (뮤즈)",
        "The New Bonnet": "새 보닛",
        "Panoramic View of the Palace and Gardens of Versailles" : "베르사유 궁전과 정원의 파노라마 전경",
        "Cider Making" : "사과주 만들기",
        "Prisoners from the Front" : "전선에서 온 포로들",
        "The Gulf Stream" : "멕시코 만류",
        "Northeaster" : "북동풍",
        "Landscape—Scene from 'Thanatopsis'" : "풍경화:'타나톱시스'의 장면",
        "The Beeches" : "너도밤나무들",
        "George Washington" : "조지 워싱턴",
        "Autumn Oaks" : "가을 참나무들",
        "Spring Blossoms, Montclair, New Jersey" : "봄꽃, 몽클레어, 뉴저지",
        "Fur Traders Descending the Missouri" : "미주리 강을 내려오는 모피상인들",
        "A Rose" : "장미",
        "Still Life: Balsam Apple and Vegetables" : "정물화: 여주와 채소들",
        "Celia Thaxter's Garden, Isles of Shoals, Maine" : "실리아 섹스터의 정원, 쇼울스 섬, 메인",
        "Surf, Isles of Shoals" : "파도, 쇼울스 섬",
        "Central Park, Winter" : "센트럴 파크, 겨울",
        "George Washington" : "조지 워싱턴",
        "Horatio Gates" : "호레이쇼 게이츠",
        "Lady at the Tea Table" : "찻상 앞의 여인",
        "The Cup of Tea" : "차 한 잔",
        "Queen Victoria" : "빅토리아 여왕",
        "Elijah Boardman" : "일라이자 보드먼",
        "Ernesta (Child with Nurse)" : "에르네스타 (유모와 함께 있는 아이)",
        "Michael Angelo and Emma Clara Peale" : "마이클 안젤로와 엠마 클라라 필",
        "The Champion Single Sculls (Max Schmitt in a Single Scull)" : "챔피언 싱글 스컬 (싱글 스컬의 맥스 슈미트)",
        "The Thinker_ Portrait of Louis N. Kenton" : "사색가_ 루이스 N. 켄턴의 초상",
        "Portrait of a Lady" : "여인의 초상",
        "Water:moon Avalokiteshvara" : "수월관음",
        "Emperor Xuanzong's Flight to Shu" : "촉으로 도망치는 현종 황제",
        "Portrait of Shun'oku Myōha (1311–1388)" : "슌오쿠 묘하의 초상 (1311:1388)",
        "Great Indian Fruit Bat" : "인도 대과일박쥐",
        "Heart of the Andes" : "안데스의 심장",
        "The Parthenon" : "파르테논 신전",
        "The Valley of Wyoming" : "와이오밍 계곡",
        "Reclining Nude" : "누워있는 나체",
        "Street Scene in Paris (Coin de rue à Paris)" : "파리의 거리 풍경 (파리의 거리 모퉁이)",
        "Tennis at Newport" : "뉴포트에서의 테니스",
        "Mountain Stream" : "산간 개울",
        "Madame X (Madame Pierre Gautreau)" : "마담 X (마담 피에르 고트로)",
        "Mrs. Hugh Hammersley" : "휴 해머슬리 부인",
        "Fragrant Peonies of Venice" : "베니스의 향기로운 모란",
        "Summer is Coming" : "여름이 다가옵니다",
        "Red Autumn Leaves and Bridge" : "붉은 단풍과 다리",
        "Venice My Loves" : "베니스 나의 사랑들",
        "Biarritz" : "비아리츠",
        "Apples of Canada" : "캐나다의 사과",
        "Roses and Glass Bottles" : "장미와 유리병들",
        "Poppies of Armoun" : "아르마운 개양귀비꽃",
        "Rosy Life" : "장미빛 인생",
        "Luxurious Bouquet" : "호화로운 꽃다발",
        "Season of Cherries" : "체리의 계절",
        "Cosmos" : "코스모스",
        "Window of Patrasio" : "파트라시오의 창문",
        "Coast of Schiavoni" : "스키아보니의 해안",
        "Docking at Izmir" : "이즈미르에서의 정박",
        "Bouquet and Peaches" : "꽃다발과 복숭아",
        "Cherries and Flowers" : "체리와 꽃",
        "Rapeseed Field" : "유채밭",
        "Cannes and Cheque" : "칸과 쉬케",
        "Old Roses" : "오래된 장미",
        "Paris in Blue" : "파리 인 블루",
        "Grapes and Bouquet" : "포도와 꽃다발"
    }
    

    if title is not None:
        title = TITLE_TRANSLATIONS.get(title, title) # title이 있으면 찾아 바꾸고 아니면 원문 반환
        print(title)
    
    if artist is not None:
        artist = ARTIST_TRANSLATIONS.get(artist, artist) # artist가 있으면 찾아 바꾸고 아니면 원문 반환
        print(artist)
    
    return title, artist